image:
  file: .gitpod.Dockerfile

tasks:
  - init: cabal update && cabal install unordered-containers

vscode:
  extensions:
    - phoityne.phoityne-vscode@0.0.24:FTkd1r93lYs3z95fjRROAg==
    - hoovercj.haskell-linter@0.0.6:VpJluXvOyr9Iw7TIKg2Oyg==
    - dramforever.vscode-ghc-simple@0.1.13:X3A6Dr3LYAP8MxXBh/hb1A==
    - justusadam.language-haskell@3.3.0:uqgpHstOoamig+7LyFNNVw==