image:
  file: sourcegraph/haskell-ide-engine
tasks:
  - init: cabal update && cabal install unordered-containers

vscode:
  extensions:
    - justusadam.language-haskell@2.6.0:CvYnp3YmQPTuto0m1di+1A==
    - phoityne.phoityne-vscode@0.0.24:FTkd1r93lYs3z95fjRROAg==
    - hoovercj.haskell-linter@0.0.6:VpJluXvOyr9Iw7TIKg2Oyg==
    - dramforever.vscode-ghc-simple@0.1.13:X3A6Dr3LYAP8MxXBh/hb1A==
